# Numpy Practice 

### Do The following :
- Finish the practice
- share it on your github account
- notify me at m.kutbi@seu.edu.sa if you faced any difficulties or when you finish

#### Write the code that will produce the requested output or action as you see on the following cell

In [ ]:
## For example 
## to get the output Hello, Mohammed
print("Hello, Mohammed") ## TODO

### import the package numpy and make the shortcut "np" for it. 

In [6]:
import numpy as np

#### define a numpy array [1, 2, 3, 4, 5] and assign it to variable x 

In [7]:
x = np.array([1, 2, 3, 4, 5])

### Print x 

In [8]:
print(x)

[1 2 3 4 5]


### Print the mean of x using numpy 

In [9]:
print(np.mean(x))

3.0


### Print the maximum number in array x

In [10]:
print(np.max(x))

5


### Generate a random number between 35 and 40

In [34]:
rand_num = np.random.randint(35, 40)
# print(rand_num)

37


### generate a list (N) of 1000 numbers with random values between 100 and 150  

In [45]:
rand_list = np.random.random_sample(1000) * 50 + 100
# print(rand_list)

[141.11429858 142.0035018  125.21593457 119.68295552 124.51489863
 124.71799067 114.07392778 107.27211632 142.08350995 100.99814967]


### get the mean, median, std, and variance of the list N 

In [46]:
rand_list_mean = np.mean(rand_list)
rand_list_median = np.median(rand_list)
rand_list_std = np.std(rand_list)
rand_list_var = np.var(rand_list)
# print(rand_list_mean, rand_list_median, rand_list_std, rand_list_var)

124.16772835035049 124.61644465227121 13.682424561214543 187.20874187332697


### generate a 2D array of size 3 x 4 of random numbers between 18-65 

In [52]:
rand_2D = np.random.rand(3, 4) * 18 + 47
print(rand_2D)

[[53.85057065 52.44338738 61.29953125 58.31831579]
 [57.31052311 63.17719992 47.02414634 61.15413548]
 [56.05481094 54.37394627 60.85197149 51.62615305]]


### Get the mean for every columns N

In [64]:
print(np.mean(rand_2D,0))

[55.7386349  56.66484452 56.39188302 57.0328681 ]


### Get the mean for every row of N 


In [72]:
i = 0
while i < 3:
    print(np.mean(rand_2D[i]))
    i+=1

56.47795126549017
57.16650121153451
55.7267204361103


### Create the following 2D array (S) of students grade in a classroom
- grades [coursework, midterm exam, final exam]
- [20, 15, 40]
- [25, 24, 35]
- [21, 15, 25]

In [78]:
s = np.array( [
    [20, 15, 40],
    [25, 24, 35],
    [21, 15, 25]
])


### Get the sums of student grades in S

In [82]:
sum_of_grades = sum(s)

### Get the means of student grades in every activity (coursework, midterm exam, final exam) in S

In [84]:
mean_of_grades = np.mean(s,0)


### reshape S in a way that make the colums represent the students and rows represent the activity, as follow
- [20, 25, 21] 
- [15, 24, 15]
- [40, 35, 25]

In [86]:
np.transpose(s)

[[20 25 21]
 [15 24 15]
 [40 35 25]]


# Pandas Practice 

### import the package pandas and make the shortcut "pd" for it. 

In [93]:
! pip install pandas

In [94]:
import pandas as pd

### create Series call it (Data) with the values 'a','b','d','u' and 'l'

In [99]:
dataset = ['a', 'b', 'd', 'u', 'i']
Data = pd.Series(dataset)
# print(Data)

0    a
1    b
2    d
3    u
4    i
dtype: object


### change index to 3,6,9,12, and 15 for (data) 

In [104]:
Data = pd.Series(dataset, index = [3, 6, 9, 12, 15])
# print(Data)

3     a
6     b
9     d
12    u
15    i
dtype: object


# change index to client1, client2, client3, client4 and client5 for (data) 

In [105]:
Data = pd.Series(dataset, index = ["client1", "client2", "client3", "client4", "client5"])
# print(Data)

client1    a
client2    b
client3    d
client4    u
client5    i
dtype: object


### create a dataframe (D) with the followin values
- 	Name -	Age
-   Ali	 -  55
- 	Ahmad -	15
- 	Nora -	40

In [107]:
D = pd.DataFrame([ ["Ali", 55] , ["Ahmed", 15] , ["Noura", 40] ], columns = ["Name", "Age"])
print(D)

    Name  Age
0    Ali   55
1  Ahmed   15
2  Noura   40


### Get the means of ages of people in (D)

In [111]:
## TODO expected value is 36.66
print(D.mean())

Age    36.666667
dtype: float64
